/**
 * AGRO DEMETRA — Каталог Фунгициди (36 реални продукта)
 * Базирано на реалния регистър на БАБХ и анализ на българския агроаптечен пазар.
 */
window.AGRO_CATALOG_DATA = window.AGRO_CATALOG_DATA || [];

const FUNGICIDES = [
  {
    id: "luna-care-vg",
    name: "Луна Кеър ВГ",
    title: "Луна Кеър ВГ – системен фунгицид с флуопирам и фозетил-Al",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 66.41,
    unit: "1 кг",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Ябълки, Круши",
    active: "Флуопирам (50 г/кг) + Фозетил-Al (666 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "14 дни (Лозя) / 28 дни (Ябълки)",
    reg: "БАБХ: № 01642-ПРЗ",
    badge: "Топ Избор",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Високоефективен фунгицид с предпазно и системно лечебно действие за контрол на брашнеста мана (оидиум) и струпясване при ябълки.",
    rates: [
      { val: 200, label: "200 г/дка (Оидиум по лозя)" },
      { val: 250, label: "250 г/дка (Струпясване и бактериален пригор при семкови)" }
    ],
    packSizes: [
      { label: "100 г", price: 9.31, unit: "€ 9.80 / 100 г" },
      { label: "1 кг", price: 66.41, unit: "€ 69.90 / 1 кг", default: true }
    ],
    rating: 4.9,
    reviewsCount: 42,
    inStock: true
  },
  {
    id: "luna-experience",
    name: "Луна Експириънс СК",
    title: "Луна Експириънс СК – системен фунгицид с флуопирам и тебуконазол",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 70.77,
    unit: "1 л",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Ябълки, Праскови, Череши, Домати",
    active: "Флуопирам (200 г/л) + Тебуконазол (200 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "14 дни (Овощни) / 7 дни (Домати)",
    reg: "БАБХ: № 01488-ПРЗ",
    badge: "Премиум Защита",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Комбиниран фунгицид срещу брашнеста мана, ранно и късно кафяво гниене, бяла ръжда и струпясване.",
    rates: [
      { val: 40, label: "40 мл/дка (Оидиум по лозя)" },
      { val: 60, label: "60 мл/дка (Кафяво гниене по костилкови)" }
    ],
    packSizes: [
      { label: "100 мл", price: 10.64, unit: "€ 11.20 / 100 мл" },
      { label: "1 л", price: 70.77, unit: "€ 74.50 / 1 л", default: true }
    ],
    rating: 4.9,
    reviewsCount: 38,
    inStock: true
  },
  {
    id: "score-250-ek",
    name: "Скор 250 ЕК",
    title: "Скор 250 ЕК – системен триазолов фунгицид с дифеноконазол",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 5.32,
    unit: "20 мл",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["овощни", "домати", "лозя"],
    cropsDisplay: "Овощни, Домати, Лозя, Захарно цвекло",
    active: "Дифеноконазол (250 г/л)",
    formulation: "ЕК (Емулсионен концентрат)",
    quarantine: "14 дни (Овощни) / 3 дни (Домати)",
    reg: "БАБХ: № 00312-ПРЗ",
    badge: "Еталон Струпясване",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Златен стандарт срещу струпясване по ябълка и круша, ранно кафяво гниене и алтернария (ран листен пригор).",
    rates: [
      { val: 20, label: "20 мл/дка (Струпясване и алтернария)" },
      { val: 30, label: "30 мл/дка (Брашнеста мана)" }
    ],
    packSizes: [
      { label: "20 мл", price: 5.32, unit: "€ 5.60 / 20 мл", default: true },
      { label: "250 мл", price: 39.90, unit: "€ 42.00 / 250 мл" },
      { label: "1 л", price: 140.60, unit: "€ 148.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 56,
    inStock: true
  },
  {
    id: "topaz-100-ek",
    name: "Топаз 100 ЕК",
    title: "Топаз 100 ЕК – фунгицид с газово действие с пенконазол",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 3.61,
    unit: "10 мл",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Ябълки, Праскови, Краставици",
    active: "Пенконазол (100 г/л)",
    formulation: "ЕК (Емулсионен концентрат)",
    quarantine: "14 дни (Лозя) / 3 дни (Краставици)",
    reg: "БАБХ: № 00215-ПРЗ",
    badge: "Газова Фаза",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Изключително ефикасен системен фунгицид с газова фаза за стопиране на оидиум и брашнести мани.",
    rates: [
      { val: 25, label: "25-30 мл/дка (Оидиум по лозя)" },
      { val: 40, label: "40 мл/дка (Брашнеста мана по праскови)" }
    ],
    packSizes: [
      { label: "10 мл", price: 3.61, unit: "€ 3.80 / 10 мл", default: true },
      { label: "100 мл", price: 17.57, unit: "€ 18.50 / 100 мл" },
      { label: "1 л", price: 77.90, unit: "€ 82.00 / 1 л" }
    ],
    rating: 4.8,
    reviewsCount: 31,
    inStock: true
  },
  {
    id: "shavit-f-72-vdg",
    name: "Шавит Ф 72 ВДГ",
    title: "Шавит Ф 72 ВДГ – контактно-системен фунгицид с фолпет и триадименол",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 17.48,
    unit: "1 кг",
    brand: "adama",
    brandName: "ADAMA Agricultural Solutions",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Ябълки, Круши",
    active: "Фолпет (700 г/кг) + Триадименол (20 г/кг)",
    formulation: "ВДГ (Вододиспергируеми гранули)",
    quarantine: "20 дни (Лозя) / 14 дни (Ябълки)",
    reg: "БАБХ: № 00890-ПРЗ",
    badge: "Двойно Действие",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Едновременна защита срещу мана (плазмопара) и оидиум (брашнеста мана) при лозя с едно пръскане.",
    rates: [
      { val: 200, label: "200 г/дка (Мана и оидиум по лозя)" },
      { val: 200, label: "200 г/дка (Струпясване и брашнеста мана по ябълка)" }
    ],
    packSizes: [
      { label: "100 г", price: 2.75, unit: "€ 2.90 / 100 г" },
      { label: "1 кг", price: 17.48, unit: "€ 18.40 / 1 кг", default: true }
    ],
    rating: 4.9,
    reviewsCount: 64,
    inStock: true
  },
  {
    id: "ridomil-gold-r",
    name: "Ридомил Голд Р ВГ",
    title: "Ридомил Голд Р ВГ – системен фунгицид с мефеноксам и меден оксихлорид",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 36.57,
    unit: "1 кг",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "картофи", "домати"],
    cropsDisplay: "Лозя, Картофи, Домати, Тютюн",
    active: "Мефеноксам (20 г/кг) + Меден оксихлорид (141.9 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "20 дни (Лозя) / 7 дни (Зеленчуци)",
    reg: "БАБХ: № 01340-ПРЗ",
    badge: "Анти-Мана",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Лидерът срещу обикновена мана и картофена мана (фитофтора) с бързо поемане за 30 минути.",
    rates: [
      { val: 500, label: "500 г/дка (Мана по лозя)" },
      { val: 500, label: "500 г/дка (Картофена мана по картофи и домати)" }
    ],
    packSizes: [
      { label: "250 г", price: 10.92, unit: "€ 11.50 / 250 г" },
      { label: "1 кг", price: 36.57, unit: "€ 38.50 / 1 кг", default: true },
      { label: "5 кг", price: 166.25, unit: "€ 35.00 / кг" }
    ],
    rating: 5.0,
    reviewsCount: 78,
    inStock: true
  },
  {
    id: "quadris-25-sk",
    name: "Куадрис 25 СК",
    title: "Куадрис 25 СК – стробилуринов фунгицид с азоксистробин",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 45.60,
    unit: "1 л",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "домати", "картофи"],
    cropsDisplay: "Лозя, Домати, Краставици, Картофи, Пипер",
    active: "Азоксистробин (250 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "7 дни (Лозя) / 3 дни (Зеленчуци)",
    reg: "БАБХ: № 00645-ПРЗ",
    badge: "Широк Спектър",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Едновременно предпазва от мани, оидиум, алтернария, черни листни петна и осигурява зелен ефект.",
    rates: [
      { val: 80, label: "80 мл/дка (Обикновена и брашнеста мана по лозя)" },
      { val: 80, label: "80-100 мл/дка (Алтернария и фитофтора по домати)" }
    ],
    packSizes: [
      { label: "20 мл", price: 2.66, unit: "€ 2.80 / 20 мл" },
      { label: "100 мл", price: 8.46, unit: "€ 8.90 / 100 мл" },
      { label: "1 л", price: 45.60, unit: "€ 48.00 / 1 л", default: true }
    ],
    rating: 4.8,
    reviewsCount: 45,
    inStock: true
  },
  {
    id: "bordeaux-mixture",
    name: "Бордолезов разтвор 20 ВП",
    title: "Бордолезов разтвор 20 ВП – неутрализиран меден сулфат",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 7.79,
    unit: "1 кг",
    brand: "manica",
    brandName: "Manica SpA (Италия)",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "домати"],
    cropsDisplay: "Лозя, Овощни дървета, Домати, Картофи",
    active: "Мед (под формата на триосновен меден сулфат 20%)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "21 дни (Лозя) / 14 дни (Овощни)",
    reg: "БАБХ: № 00104-ПРЗ",
    badge: "Био Разрешен",
    image: "https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80",
    desc: "Класически готов неутрализиран меден препарат за ранни предцъфтежни и есенни пръскания срещу сачмянка, къдравост и мана.",
    rates: [
      { val: 1500, label: "1.5% (1.5 кг / 100 л вода при покой)" },
      { val: 750, label: "0.75% (750 г / 100 л вода през вегетацията)" }
    ],
    packSizes: [
      { label: "1 кг", price: 7.79, unit: "€ 8.20 / 1 кг", default: true },
      { label: "5 кг", price: 34.20, unit: "€ 7.20 / кг" },
      { label: "25 кг", price: 156.75, unit: "€ 6.60 / кг" }
    ],
    rating: 4.9,
    reviewsCount: 89,
    inStock: true
  },
  {
    id: "dithane-m-45",
    name: "Дитан М-45 ВП",
    title: "Дитан М-45 ВП – контактен фунгицид с манкозеб 80%",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 12.82,
    unit: "1 кг",
    brand: "corteva",
    brandName: "Corteva Agriscience",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "картофи", "домати", "овощни"],
    cropsDisplay: "Лозя, Домати, Картофи, Тютюн, Овощни",
    active: "Манкозеб (800 г/кг)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "20 дни (Лозя) / 7 дни (Картофи)",
    reg: "БАБХ: № 00052-ПРЗ",
    badge: "Класически Щит",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Контактен широкоспектърен защитен фунгицид с микроелементи цинк и манган срещу мани и алтернария.",
    rates: [
      { val: 200, label: "200-250 г/дка (Мана и струпясване)" },
      { val: 200, label: "200 г/дка (Картофена мана)" }
    ],
    packSizes: [
      { label: "250 г", price: 3.99, unit: "€ 4.20 / 250 г" },
      { label: "1 кг", price: 12.82, unit: "€ 13.50 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 39,
    inStock: true
  },
  {
    id: "cabrio-top",
    name: "Кабрио Топ ВГ",
    title: "Кабрио Топ ВГ – комбиниран фунгицид с метирам и пираклостробин",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 47.40,
    unit: "1 кг",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "домати"],
    cropsDisplay: "Лозя, Домати",
    active: "Метирам (550 г/кг) + Пираклостробин (50 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "28 дни (Лозя) / 7 дни (Домати)",
    reg: "БАБХ: № 00922-ПРЗ",
    badge: "AgCelence Ефект",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Двойна защита с AgCelence физиологичен ефект за лозя срещу обикновена мана, оидиум, червеница и черно гниене.",
    rates: [
      { val: 200, label: "150-200 г/дка (Мана, оидиум и сиво гниене)" }
    ],
    packSizes: [
      { label: "200 г", price: 11.88, unit: "€ 12.50 / 200 г" },
      { label: "1 кг", price: 47.40, unit: "€ 49.90 / 1 кг", default: true }
    ],
    rating: 4.9,
    reviewsCount: 52,
    inStock: true
  },
  {
    id: "flint-max-75-vg",
    name: "Флинт Макс 75 ВГ",
    title: "Флинт Макс 75 ВГ – трифлоксистробин и тебуконазол за лозя и овощни",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 34.67,
    unit: "500 г",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Ябълки, Круши, Череши",
    active: "Трифлоксистробин (500 г/кг) + Тебуконазол (250 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "14 дни (Лозя и ябълки) / 7 дни (Череши)",
    reg: "БАБХ: № 01132-ПРЗ",
    badge: "Мезосистемен",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Мезосистемен препарат с бързо задържане върху восъчния налеп на листата и мощно изпарение срещу оидиум и бяла ръжда.",
    rates: [
      { val: 16, label: "16 г/дка (Оидиум и черно гниене)" },
      { val: 20, label: "20 г/дка (Струпясване и брашнеста мана)" }
    ],
    packSizes: [
      { label: "50 г", price: 5.13, unit: "€ 5.40 / 50 г" },
      { label: "500 г", price: 34.67, unit: "€ 36.50 / 500 г", default: true }
    ],
    rating: 4.8,
    reviewsCount: 27,
    inStock: true
  },
  {
    id: "switch-62-5-vg",
    name: "Суич 62.5 ВГ",
    title: "Суич 62.5 ВГ – специализиран фунгицид срещу сиво гниене",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 16.05,
    unit: "100 г",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "зеленчуци", "овощни"],
    cropsDisplay: "Лозя, Ягоди, Малини, Домати, Пипер",
    active: "Ципродинил (375 г/кг) + Флудиоксонил (250 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "21 дни (Лозя) / 3 дни (Ягоди, Домати)",
    reg: "БАБХ: № 00810-ПРЗ",
    badge: "№1 Сиво Гниене",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Ненадминат ботритицид за защита на гроздето и ягодите при затваряне на грозда и преди узряване.",
    rates: [
      { val: 100, label: "100 г/дка (Сиво гниене Botrytis cinerea)" },
      { val: 80, label: "80 г/дка (Бяло гниене Sclerotinia)" }
    ],
    packSizes: [
      { label: "10 г", price: 2.56, unit: "€ 2.70 / 10 г" },
      { label: "100 г", price: 16.05, unit: "€ 16.90 / 100 г", default: true },
      { label: "1 кг", price: 134.90, unit: "€ 142.00 / 1 кг" }
    ],
    rating: 5.0,
    reviewsCount: 71,
    inStock: true
  },
  {
    id: "sercadis",
    name: "Серкадис СК",
    title: "Серкадис СК – иновативен фунгицид с активно вещество Xemium",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 83.60,
    unit: "1 л",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["овощни", "лозя"],
    cropsDisplay: "Ябълка, Круша, Праскова, Лозя",
    active: "Флуксапироксад (Ксемиум) 300 г/л",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "35 дни (Лозя) / 7 дни (Ябълки)",
    reg: "БАБХ: № 01540-ПРЗ",
    badge: "SDHI Иновация",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Най-гъвкавата SDHI молекула с мобилност във всяка растителна клетка срещу струпясване и брашнеста мана.",
    rates: [
      { val: 25, label: "25-30 мл/дка (Струпясване и оидиум)" }
    ],
    packSizes: [
      { label: "1 л", price: 83.60, unit: "€ 88.00 / 1 л", default: true }
    ],
    rating: 4.9,
    reviewsCount: 19,
    inStock: true
  },
  {
    id: "bellis",
    name: "Белис ВГ",
    title: "Белис ВГ – боскалид и пираклостробин за съхранение на ябълки",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 60.80,
    unit: "1 кг",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["овощни"],
    cropsDisplay: "Ябълки, Круши",
    active: "Боскалид (252 г/кг) + Пираклостробин (128 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "7 дни",
    reg: "БАБХ: № 00875-ПРЗ",
    badge: "За Дълго Съхранение",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Предпазва плодовете от гниене и горчиви петна както на полето, така и по време на лагеруване в хладилни камери.",
    rates: [
      { val: 80, label: "80 г/дка (Струпясване, брашнеста мана и гниене при съхранение)" }
    ],
    packSizes: [
      { label: "1 кг", price: 60.80, unit: "€ 64.00 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 22,
    inStock: true
  },
  {
    id: "infinito",
    name: "Инфинито СК",
    title: "Инфинито СК – системен фунгицид с флуопиколид и пропамокарб",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 41.32,
    unit: "1 л",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["картофи", "зеленчуци"],
    cropsDisplay: "Картофи, Домати, Краставици, Зеле",
    active: "Флуопиколид (62.5 г/л) + Пропамокарб хидрохлорид (625 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "7 дни (Картофи) / 3 дни (Краставици)",
    reg: "БАБХ: № 00723-ПРЗ",
    badge: "Анти-Фитофтора",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Пълен контрол на маната по клубените на картофите и листната маса на зеленчуците.",
    rates: [
      { val: 120, label: "120-160 мл/дка (Мана по картофи Phytophthora infestans)" },
      { val: 140, label: "140 мл/дка (Кубинска мана по краставици)" }
    ],
    packSizes: [
      { label: "100 мл", price: 6.55, unit: "€ 6.90 / 100 мл" },
      { label: "1 л", price: 41.32, unit: "€ 43.50 / 1 л", default: true }
    ],
    rating: 4.9,
    reviewsCount: 35,
    inStock: true
  },
  {
    id: "revus-250-sk",
    name: "Ревус 250 СК",
    title: "Ревус 250 СК – локал-системен фунгицид с мандипропамид",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 49.40,
    unit: "1 л",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["картофи", "домати", "лозя"],
    cropsDisplay: "Картофи, Домати, Лозя",
    active: "Мандипропамид (250 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "3 дни (Домати) / 7 дни (Картофи) / 21 дни (Лозя)",
    reg: "БАБХ: № 01015-ПРЗ",
    badge: "LOK-FLO Технология",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Свързва се трайно с восъчния налеп на листата и не се отмива дори от силен дъжд 1 час след третиране.",
    rates: [
      { val: 50, label: "50-60 мл/дка (Мана по картофи и домати)" }
    ],
    packSizes: [
      { label: "250 мл", price: 15.67, unit: "€ 16.50 / 250 мл" },
      { label: "1 л", price: 49.40, unit: "€ 52.00 / 1 л", default: true }
    ],
    rating: 4.8,
    reviewsCount: 29,
    inStock: true
  },
  {
    id: "kocide-2000",
    name: "Косайд 2000 ВГ",
    title: "Косайд 2000 ВГ – биосъвместим меден хидроксид 53.8%",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 23.56,
    unit: "1 кг",
    brand: "corteva",
    brandName: "Corteva Agriscience",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "домати"],
    cropsDisplay: "Лозя, Овощни, Домати, Картофи, Орехи",
    active: "Меден хидроксид (53.8% с 35% чиста метална мед)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "14 дни (Лозя) / 7 дни (Домати)",
    reg: "БАБХ: № 00812-ПРЗ",
    badge: "Био Стандарт",
    image: "https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80",
    desc: "Най-фините медни частици на пазара за максимална покривност и отлична устойчивост на отмиване.",
    rates: [
      { val: 155, label: "155-200 г/дка (Мана по лозя и бактериози)" },
      { val: 200, label: "200-250 г/дка (Овощни дървета при набъбване на пъпките)" }
    ],
    packSizes: [
      { label: "1 кг", price: 23.56, unit: "€ 24.80 / 1 кг", default: true },
      { label: "5 кг", price: 106.40, unit: "€ 22.40 / кг" }
    ],
    rating: 4.9,
    reviewsCount: 47,
    inStock: true
  },
  {
    id: "funguran-on-50",
    name: "Фунгуран ОН 50 ВП",
    title: "Фунгуран ОН 50 ВП – контактен меден фунгицид с меден хидроксид",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 18.90,
    unit: "1 кг",
    brand: "manica",
    brandName: "Spiess Urania / Manica",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Домати, Картофи, Овощни",
    active: "Меден хидроксид (50% чиста мед)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "14 дни (Лозя) / 7 дни (Зеленчуци)",
    reg: "БАБХ: № 00330-ПРЗ",
    badge: "Био Мед",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Ефикасен срещу ранно кафяво гниене, къдравост по праскова, бактериози и мани.",
    rates: [
      { val: 200, label: "150-200 г/дка (Мана по лозя)" },
      { val: 250, label: "250 г/дка (Зимно пръскане на овощни)" }
    ],
    packSizes: [
      { label: "150 г", price: 3.70, unit: "€ 3.90 / 150 г" },
      { label: "1 кг", price: 18.90, unit: "€ 19.90 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 33,
    inStock: true
  },
  {
    id: "champion-50-vp",
    name: "Шампион 50 ВП",
    title: "Шампион 50 ВП – контактен меден фунгицид (Меден хидроксид 77%)",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 17.29,
    unit: "1 кг",
    brand: "manica",
    brandName: "Nufarm / Manica",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Ябълки, Праскови, Домати",
    active: "Меден хидроксид (77% съответстващ на 50% Cu)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "14 дни (Лозя) / 7 дни (Домати)",
    reg: "БАБХ: № 00115-ПРЗ",
    badge: "Традиция",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Надеждна защита от бактериални и гъбни инфекции. Идеален за измиващо предцъфтежно пръскане.",
    rates: [
      { val: 150, label: "150 г/дка (Мана по лозя и домати)" },
      { val: 300, label: "300 г/дка (Къдравост по прасковата)" }
    ],
    packSizes: [
      { label: "150 г", price: 3.32, unit: "€ 3.50 / 150 г" },
      { label: "1 кг", price: 17.29, unit: "€ 18.20 / 1 кг", default: true }
    ],
    rating: 4.9,
    reviewsCount: 40,
    inStock: true
  },
  {
    id: "vitisan",
    name: "Витисан БИО",
    title: "Витисан – контактен биофунгицид с калиев хидроген карбонат",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 11.30,
    unit: "1 кг",
    brand: "amitica",
    brandName: "Andermatt Biocontrol / Амитица",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозе, Овощни, Зеленчуци, Ягоди",
    active: "Калиев хидроген карбонат (995 г/кг)",
    formulation: "СП (Разтворим прах)",
    quarantine: "1 ден",
    reg: "БАБХ: № 01588-ПРЗ",
    badge: "100% БИО",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Сертифициран за биологично земеделие продукт срещу оидиум, сиво гниене и струпясване. Карантинен срок само 1 ден!",
    rates: [
      { val: 500, label: "500-1000 г/дка (Оидиум и сиво гниене)" }
    ],
    packSizes: [
      { label: "1 кг", price: 11.30, unit: "€ 11.90 / 1 кг", default: true },
      { label: "5 кг", price: 49.40, unit: "€ 10.40 / кг" }
    ],
    rating: 4.9,
    reviewsCount: 36,
    inStock: true
  },
  {
    id: "melody-compact",
    name: "Мелоди Компакт 49 ВГ",
    title: "Мелоди Компакт 49 ВГ – ипроваликарб с меден оксихлорид",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 27.07,
    unit: "1 кг",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "домати", "картофи"],
    cropsDisplay: "Лозя, Домати, Картофи",
    active: "Ипроваликарб (84 г/кг) + Меден оксихлорид (406 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "20 дни (Лозя) / 7 дни (Домати)",
    reg: "БАБХ: № 00980-ПРЗ",
    badge: "Стоп Мана",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Комбиниран препарат с лечебно действие до 48 часа след заразяване с мана.",
    rates: [
      { val: 150, label: "150-175 г/дка (Мана по лозя и домати)" }
    ],
    packSizes: [
      { label: "150 г", price: 5.51, unit: "€ 5.80 / 150 г" },
      { label: "1 кг", price: 27.07, unit: "€ 28.50 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 25,
    inStock: true
  },
  {
    id: "cantus",
    name: "Кантус ВГ",
    title: "Кантус ВГ – боскалид срещу сиво гниене по гроздето",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 68.40,
    unit: "1 кг",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя"],
    cropsDisplay: "Винен и десертен сорт лозя",
    active: "Боскалид (500 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "28 дни (Винени) / 21 дни (Десертни)",
    reg: "БАБХ: № 00744-ПРЗ",
    badge: "Спец Лозя",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Специфичен фунгицид с пълен блокаж на гъбата Botrytis cinerea, осигуряващ чист гроздов сок за качествено вино.",
    rates: [
      { val: 100, label: "100-120 г/дка (Сиво гниене при оформяне и узряване на грозда)" }
    ],
    packSizes: [
      { label: "100 г", price: 9.40, unit: "€ 9.90 / 100 г" },
      { label: "1 кг", price: 68.40, unit: "€ 72.00 / 1 кг", default: true }
    ],
    rating: 4.9,
    reviewsCount: 18,
    inStock: true
  },
  {
    id: "scala",
    name: "Скала СК",
    title: "Скала СК – фунгицид с пириметанил за лозя и овощни",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 51.30,
    unit: "1 л",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Ябълки, Круши, Ягоди",
    active: "Пириметанил (400 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "21 дни (Лозя) / 7 дни (Ябълки)",
    reg: "БАБХ: № 00818-ПРЗ",
    badge: "Работи при Студ",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Действа безотказно дори при ниски температури от 5°C, когато другите фунгициди спират да работят.",
    rates: [
      { val: 150, label: "150-200 мл/дка (Сиво гниене и струпясване)" }
    ],
    packSizes: [
      { label: "1 л", price: 51.30, unit: "€ 54.00 / 1 л", default: true }
    ],
    rating: 4.8,
    reviewsCount: 20,
    inStock: true
  },
  {
    id: "systhane-ecozom",
    name: "Систан Екозом ЕВ",
    title: "Систан Екозом ЕВ – системен фунгицид с миклобутанил 20%",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 8.07,
    unit: "50 мл",
    brand: "corteva",
    brandName: "Corteva Agriscience",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Ябълка, Рози, Краставици",
    active: "Миклобутанил (200 г/л)",
    formulation: "ЕВ (Емулсия вода в масло)",
    quarantine: "14 дни (Лозя и ябълки) / 3 дни (Краставици)",
    reg: "БАБХ: № 01420-ПРЗ",
    badge: "Лечебно Действие",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Мощно системно лечебно действие до 96 часа след заразяване срещу брашнеста мана (оидиум), струпясване и ръжди.",
    rates: [
      { val: 20, label: "20-25 мл/дка (Оидиум по лозя)" },
      { val: 30, label: "30 мл/дка (Брашнеста мана по рози и зеленчуци)" }
    ],
    packSizes: [
      { label: "50 мл", price: 8.07, unit: "€ 8.50 / 50 мл", default: true },
      { label: "1 л", price: 84.55, unit: "€ 89.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 34,
    inStock: true
  },
  {
    id: "tiovit-jet",
    name: "Тиовит Джет 80 ВГ",
    title: "Тиовит Джет 80 ВГ – микронизирана сяра с акарицидно действие",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 4.27,
    unit: "1 кг",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Ябълки, Праскови, Зеленчуци",
    active: "Микронизирана сяра (800 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "14 дни (Лозя) / 3 дни (Зеленчуци)",
    reg: "БАБХ: № 00021-ПРЗ",
    badge: "Био + Акари",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Универсална водоразтворима сяра. Едновременно контролира брашнеста мана и потиска развитието на акари.",
    rates: [
      { val: 300, label: "300 г/дка (Оидиум по лозя)" },
      { val: 600, label: "600 г/дка (При силно нападение и акари)" }
    ],
    packSizes: [
      { label: "1 кг", price: 4.27, unit: "€ 4.50 / 1 кг", default: true },
      { label: "5 кг", price: 18.52, unit: "€ 3.90 / кг" },
      { label: "25 кг", price: 75.05, unit: "€ 3.16 / кг" }
    ],
    rating: 4.9,
    reviewsCount: 63,
    inStock: true
  },
  {
    id: "kumulus-df",
    name: "Кумулус ДФ",
    title: "Кумулус ДФ – чиста колоидна сяра 80% от BASF",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 4.37,
    unit: "1 кг",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Овощни култури",
    active: "Сяра (800 г/кг)",
    formulation: "ВДГ (Вододиспергируеми гранули)",
    quarantine: "14 дни",
    reg: "БАБХ: № 00035-ПРЗ",
    badge: "Без Прах",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Гранулирана формула без прашене, с отлично газово изпарение и подхранващ ефект за лозята.",
    rates: [
      { val: 300, label: "300-500 г/дка (Оидиум по лозя)" }
    ],
    packSizes: [
      { label: "1 кг", price: 4.37, unit: "€ 4.60 / 1 кг", default: true },
      { label: "25 кг", price: 77.90, unit: "€ 3.28 / кг" }
    ],
    rating: 4.8,
    reviewsCount: 30,
    inStock: true
  },
  {
    id: "prolectus-50-vg",
    name: "Пролектус 50 ВГ",
    title: "Пролектус 50 ВГ – фенпиразамин срещу кафяво и сиво гниене",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 37.05,
    unit: "500 г",
    brand: "syngenta",
    brandName: "Kenogard / Syngenta",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["овощни", "лозя", "зеленчуци"],
    cropsDisplay: "Праскови, Нектарини, Череши, Домати, Лозя",
    active: "Фенпиразамин (500 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "1 ден (Домати, Праскови) / 14 дни (Лозя)",
    reg: "БАБХ: № 01490-ПРЗ",
    badge: "1 Ден Карантина",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Ултра кратка карантина от 1 ден при праскови и домати. Спира покълването на спорите мигновено.",
    rates: [
      { val: 80, label: "80-120 г/дка (Монилиоза и сиво гниене)" }
    ],
    packSizes: [
      { label: "100 г", price: 9.03, unit: "€ 9.50 / 100 г" },
      { label: "500 г", price: 37.05, unit: "€ 39.00 / 500 г", default: true }
    ],
    rating: 4.9,
    reviewsCount: 21,
    inStock: true
  },
  {
    id: "cuprocine-mz",
    name: "Купроцин МЗ",
    title: "Купроцин МЗ ВП – мед и манкозеб срещу всички видове мани",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 13.49,
    unit: "1 кг",
    brand: "manica",
    brandName: "Агрия АД / Manica",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "домати", "картофи"],
    cropsDisplay: "Лозя, Домати, Картофи, Пипер",
    active: "Мед (под формата на меден оксихлорид 15%) + Манкозеб (15%)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "20 дни (Лозя) / 14 дни (Зеленчуци)",
    reg: "БАБХ: № 00140-ПРЗ",
    badge: "Български Класик",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Доказана комбинация между органичен и неорганичен контактен фунгицид за пълно покриване и бактерициден ефект.",
    rates: [
      { val: 250, label: "250-300 г/дка (Мана и черни листни петна)" }
    ],
    packSizes: [
      { label: "250 г", price: 4.27, unit: "€ 4.50 / 250 г" },
      { label: "1 кг", price: 13.49, unit: "€ 14.20 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 50,
    inStock: true
  },
  {
    id: "propulse-250-se",
    name: "Пропулс 250 СЕ",
    title: "Пропулс 250 СЕ – фунгицид с флуопирам и протиоконазол",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 55.10,
    unit: "1 л",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["житни"],
    cropsDisplay: "Рапица, Слънчоглед, Царевица, Соя",
    active: "Флуопирам (125 г/л) + Протиоконазол (125 г/л)",
    formulation: "СЕ (Суспо-емулсия)",
    quarantine: "56 дни (Рапица)",
    reg: "БАБХ: № 01280-ПРЗ",
    badge: "Профи Полета",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Максимална реколта и контрол на бяло гниене (Sclerotinia) и фома при маслодайните култури.",
    rates: [
      { val: 100, label: "80-100 мл/дка (Склеротиния и фома)" }
    ],
    packSizes: [
      { label: "1 л", price: 55.10, unit: "€ 58.00 / 1 л", default: true },
      { label: "5 л", price: 261.25, unit: "€ 55.00 / л" }
    ],
    rating: 4.9,
    reviewsCount: 15,
    inStock: true
  },
  {
    id: "tebumax-250-ew",
    name: "Тебумакс 250 ЕВ",
    title: "Тебумакс 250 ЕВ – тебуконазол за защита на житни и лозя",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 23.27,
    unit: "1 л",
    brand: "manica",
    brandName: "Агрия АД / Manica",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["житни", "лозя", "овощни"],
    cropsDisplay: "Пшеница, Ечемик, Лозя, Рапица",
    active: "Тебуконазол (250 г/л)",
    formulation: "ЕВ (Емулсия масло във вода)",
    quarantine: "35 дни (Житни) / 21 дни (Лозя)",
    reg: "БАБХ: № 01108-ПРЗ",
    badge: "Изгоден Системен",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Широкоспектърен триазолов фунгицид с растежно-регулиращ ефект при рапица и контрол на ръжди при житни.",
    rates: [
      { val: 100, label: "100 мл/дка (Ръжди, септориоза, брашнеста мана)" },
      { val: 40, label: "40 мл/дка (Оидиум по лозя)" }
    ],
    packSizes: [
      { label: "1 л", price: 23.27, unit: "€ 24.50 / 1 л", default: true },
      { label: "5 л", price: 104.50, unit: "€ 22.00 / л" }
    ],
    rating: 4.8,
    reviewsCount: 44,
    inStock: true
  },
  {
    id: "folicur-250-ew",
    name: "Фоликур 250 ЕВ",
    title: "Фоликур 250 ЕВ – оригиналният тебуконазол от Bayer",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 30.40,
    unit: "1 л",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["житни", "овощни", "лозя"],
    cropsDisplay: "Пшеница, Рапица, Овощни, Лозя",
    active: "Тебуконазол (250 г/л)",
    formulation: "ЕВ (Емулсия масло във вода)",
    quarantine: "35 дни (Житни) / 14 дни (Овощни)",
    reg: "БАБХ: № 00210-ПРЗ",
    badge: "Оригинал Bayer",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Еталонен препарат за фузариум по класа на житните и силен антистрес ефект при есенно третиране на рапица.",
    rates: [
      { val: 100, label: "100 мл/дка (Фузариоза по класа, ръжди)" }
    ],
    packSizes: [
      { label: "1 л", price: 30.40, unit: "€ 32.00 / 1 л", default: true }
    ],
    rating: 4.9,
    reviewsCount: 37,
    inStock: true
  },
  {
    id: "polyram-df",
    name: "Полирам ДФ",
    title: "Полирам ДФ – контактен фунгицид с метирам 70%",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 14.82,
    unit: "1 кг",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "картофи", "домати", "овощни"],
    cropsDisplay: "Лозя, Картофи, Домати, Ябълки",
    active: "Метирам (700 г/кг)",
    formulation: "ВДГ (Вододиспергируеми гранули)",
    quarantine: "28 дни (Лозя) / 7 дни (Картофи)",
    reg: "БАБХ: № 00418-ПРЗ",
    badge: "С Цинк",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Контактен препарат с високо съдържание на цинк (14%), стимулиращ хлорофила и предпазващ от мана и струпясване.",
    rates: [
      { val: 200, label: "200 г/дка (Мана по лозя и картофи)" }
    ],
    packSizes: [
      { label: "1 кг", price: 14.82, unit: "€ 15.60 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 28,
    inStock: true
  },
  {
    id: "teldor-500-sc",
    name: "Телдор 500 СК",
    title: "Телдор 500 СК – специализиран фунгицид с фенхексамид",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 14.06,
    unit: "100 мл",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "зеленчуци", "ягоди"],
    cropsDisplay: "Лозя, Ягоди, Малини, Домати",
    active: "Фенхексамид (500 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "14 дни (Лозя) / 3 дни (Ягоди и домати)",
    reg: "БАБХ: № 00690-ПРЗ",
    badge: "Премиум Гниене",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Не влияе върху алкохолната ферментация и органолептичните качества на виното при защита срещу сиво гниене.",
    rates: [
      { val: 100, label: "100 мл/дка (Сиво гниене при омекване на зърното)" }
    ],
    packSizes: [
      { label: "100 мл", price: 14.06, unit: "€ 14.80 / 100 мл", default: true },
      { label: "1 л", price: 91.20, unit: "€ 96.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 31,
    inStock: true
  },
  {
    id: "folpan-80-wdg",
    name: "Фолпан 80 ВДГ",
    title: "Фолпан 80 ВДГ – контактен фунгицид с фолпет 80%",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 18.52,
    unit: "1 кг",
    brand: "adama",
    brandName: "ADAMA Agricultural Solutions",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Ябълки",
    active: "Фолпет (800 г/кг)",
    formulation: "ВДГ (Вододиспергируеми гранули)",
    quarantine: "20 дни (Лозя)",
    reg: "БАБХ: № 00712-ПРЗ",
    badge: "Без Резистентност",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Мултисайт механизъм на действие, при който патогените нямат възможност да изградят резистентност.",
    rates: [
      { val: 150, label: "150 г/дка (Мана и черно гниене по лозя)" }
    ],
    packSizes: [
      { label: "1 кг", price: 18.52, unit: "€ 19.50 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 26,
    inStock: true
  },
  {
    id: "curzate-m",
    name: "Курзат М ВГ",
    title: "Курзат М ВГ – цимоксанил и манкозеб за локално системна защита",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 19.95,
    unit: "1 кг",
    brand: "corteva",
    brandName: "Corteva Agriscience",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "картофи", "домати"],
    cropsDisplay: "Лозя, Картофи, Домати, Краставици",
    active: "Цимоксанил (4.5%) + Манкозеб (68%)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "20 дни (Лозя) / 7 дни (Картофи)",
    reg: "БАБХ: № 00390-ПРЗ",
    badge: "Бързо Спиране",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Спира маната дори когато симптомите (хлоротични петна) вече са видими по листата.",
    rates: [
      { val: 250, label: "200-250 г/дка (Обикновена мана по лозя и картофи)" }
    ],
    packSizes: [
      { label: "1 кг", price: 19.95, unit: "€ 21.00 / 1 кг", default: true }
    ],
    rating: 4.8,
    reviewsCount: 35,
    inStock: true
  },
  {
    id: "ortiva-top",
    name: "Ортива Топ СК",
    title: "Ортива Топ СК – азоксистробин и дифеноконазол за зеленчуци",
    category: "fungicides",
    categoryName: "Фунгициди",
    price: 56.05,
    unit: "1 л",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["домати", "зеленчуци", "картофи"],
    cropsDisplay: "Домати, Краставици, Моркови, Лук, Картофи",
    active: "Азоксистробин (200 г/л) + Дифеноконазол (125 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "7 дни (Домати) / 3 дни (Краставици)",
    reg: "БАБХ: № 01477-ПРЗ",
    badge: "Топ Зеленчуци",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Всичко-в-едно фунгицид за градинари: предпазва от мана, оидиум, алтернария, септориоза и ръжди едновременно.",
    rates: [
      { val: 100, label: "100 мл/дка (Брашнеста мана, алтернария и струпясване)" }
    ],
    packSizes: [
      { label: "100 мл", price: 9.31, unit: "€ 9.80 / 100 мл" },
      { label: "1 л", price: 56.05, unit: "€ 59.00 / 1 л", default: true }
    ],
    rating: 5.0,
    reviewsCount: 46,
    inStock: true
  }
];

window.AGRO_CATALOG_DATA.push(...FUNGICIDES);
