/**
 * AGRO DEMETRA — Каталог Инсектициди & Акарициди (36 реални продукта)
 * Базирано на реалния регистър на БАБХ и анализ на българския агроаптечен пазар.
 */
window.AGRO_CATALOG_DATA = window.AGRO_CATALOG_DATA || [];

const INSECTICIDES = [
  {
    id: "mospilan-20-sp",
    name: "Моспилан 20 СП",
    title: "Моспилан 20 СП – системен инсектицид с ацетамиприд",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 3.04,
    unit: "50 г",
    brand: "nippon",
    brandName: "Nippon Soda / Sumi Agro",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["домати", "картофи", "овощни", "житни"],
    cropsDisplay: "Картофи, Домати, Пипер, Овощни, Житни",
    active: "Ацетамиприд (200 г/кг)",
    formulation: "СП (Разтворим прах)",
    quarantine: "3 дни (Домати) / 7 дни (Картофи) / 14 дни (Овощни)",
    reg: "БАБХ: № 01145-ПРЗ",
    badge: "№1 Бестселър",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Най-популярният системен инсектицид в България срещу колорадски бръмбар, листни въшки, трипси и белокрилки. Безопасен за пчелите при спазване на дозата.",
    rates: [
      { val: 12.5, label: "12.5 г/дка (Листни въшки по зеленчуци)" },
      { val: 25, label: "25 г/дка (Оранжерийна белокрилка, трипс)" }
    ],
    packSizes: [
      { label: "1.5 г", price: 0.76, unit: "€ 0.80 / 1.5 г" },
      { label: "50 г", price: 3.04, unit: "€ 3.20 / 50 г", default: true },
      { label: "100 г", price: 5.61, unit: "€ 5.90 / 100 г" },
      { label: "1 кг", price: 43.70, unit: "€ 46.00 / 1 кг" }
    ],
    rating: 5.0,
    reviewsCount: 94,
    inStock: true
  },
  {
    id: "decis-100-ek",
    name: "Децис 100 ЕК",
    title: "Децис 100 ЕК – бързодействащ пиретроид с делтаметрин 100 г/л",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 3.99,
    unit: "50 мл",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци", "житни"],
    cropsDisplay: "Лозя, Овощни, Зеленчуци, Житни",
    active: "Делтаметрин (100 г/л)",
    formulation: "ЕК (Емулсионен концентрат)",
    quarantine: "3 дни (Зеленчуци) / 7 дни (Лозя, Овощни)",
    reg: "БАБХ: № 01188-ПРЗ",
    badge: "Нокдаун Ефект",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Еталонен пиретроид с мълниеносен инициален ефект и репелентно действие срещу плодови червеи, нощенки и листозавивачки.",
    rates: [
      { val: 12.5, label: "12.5 мл/дка (Шарен гроздов молец, ябълков плодов червей)" },
      { val: 17.5, label: "17.5 мл/дка (Нощенки и тютюнев трипс)" }
    ],
    packSizes: [
      { label: "50 мл", price: 3.99, unit: "€ 4.20 / 50 мл", default: true },
      { label: "250 мл", price: 15.67, unit: "€ 16.50 / 250 мл" },
      { label: "1 л", price: 51.30, unit: "€ 54.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 65,
    inStock: true
  },
  {
    id: "coragen-20-sc",
    name: "Кораген 20 СК",
    title: "Кораген 20 СК – ови-ларвицид с хлорантранилипрол (Rynaxypyr)",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 9.40,
    unit: "50 мл",
    brand: "corteva",
    brandName: "FMC Agricultural Solutions",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["домати", "картофи", "овощни", "лозя", "царевица"],
    cropsDisplay: "Картофи, Домати, Ябълки, Лозя, Царевица",
    active: "Хлорантранилипрол (200 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "1 ден (Домати) / 14 дни (Ябълки)",
    reg: "БАБХ: № 01104-ПРЗ",
    badge: "Премиум Защита",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Унищожава яйцата и ларвите на доматен миниращ молец (Tuta absoluta), царевичен пробивач и ябълков плодов червей с продължителност до 21 дни.",
    rates: [
      { val: 16, label: "16-20 мл/дка (Доматен миниращ молец Tuta absoluta)" },
      { val: 6, label: "6 мл/дка (Колорадски бръмбар по картофи)" }
    ],
    packSizes: [
      { label: "50 мл", price: 9.40, unit: "€ 9.90 / 50 мл", default: true },
      { label: "100 мл", price: 17.29, unit: "€ 18.20 / 100 мл" },
      { label: "1 л", price: 147.25, unit: "€ 155.00 / 1 л" }
    ],
    rating: 5.0,
    reviewsCount: 82,
    inStock: true
  },
  {
    id: "karate-zeon-5-cs",
    name: "Карате Зеон 5 КС",
    title: "Карате Зеон 5 КС – микрокапсулован инсектицид с ламбда-цихалотрин",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 3.32,
    unit: "50 мл",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "зеленчуци", "житни", "овощни"],
    cropsDisplay: "Лозя, Зеленчуци, Житни, Овощни",
    active: "Ламбда-цихалотрин (50 г/л)",
    formulation: "КС (Микрокапсулна суспензия)",
    quarantine: "7 дни (Зеленчуци) / 10 дни (Лозя)",
    reg: "БАБХ: № 00340-ПРЗ",
    badge: "Zeon Капсули",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Патентована Zeon капсулна технология за защита на активното вещество от UV лъчи и удължено последействие.",
    rates: [
      { val: 15, label: "15 мл/дка (Листни въшки и трипси)" },
      { val: 20, label: "20 мл/дка (Гъсеници, плодови червеи)" }
    ],
    packSizes: [
      { label: "50 мл", price: 3.32, unit: "€ 3.50 / 50 мл", default: true },
      { label: "250 мл", price: 13.49, unit: "€ 14.20 / 250 мл" },
      { label: "1 л", price: 41.80, unit: "€ 44.00 / 1 л" }
    ],
    rating: 4.8,
    reviewsCount: 57,
    inStock: true
  },
  {
    id: "sivanto-prime",
    name: "Сиванто Прайм СЛ",
    title: "Сиванто Прайм СЛ – бутенолиден инсектицид с флупирадифурон",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 7.41,
    unit: "50 мл",
    brand: "bayer",
    brandName: "Bayer Crop Science AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["домати", "зеленчуци", "овощни", "лозя"],
    cropsDisplay: "Домати, Краставици, Пипер, Ябълки, Лозя",
    active: "Флупирадифурон (200 г/л)",
    formulation: "СЛ (Разтворим концентрат)",
    quarantine: "3 дни (Домати) / 14 дни (Ябълки)",
    reg: "БАБХ: № 01512-ПРЗ",
    badge: "Пчели-Приятел",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Нов клас инсектицид, вдъхновен от естественото съединение стемофолин. Експресно блокира смучещите неприятели без да вреди на опрашителите.",
    rates: [
      { val: 50, label: "50 мл/дка (Белокрилка и листни въшки по оранжерийни зеленчуци)" },
      { val: 90, label: "90 мл/дка (Ябълкова листна бълха и цикади)" }
    ],
    packSizes: [
      { label: "50 мл", price: 7.41, unit: "€ 7.80 / 50 мл", default: true },
      { label: "1 л", price: 109.25, unit: "€ 115.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 33,
    inStock: true
  },
  {
    id: "teppeki",
    name: "Тепеки ВГ",
    title: "Тепеки ВГ – селективен системен инсектицид с флоникамид 50%",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 8.74,
    unit: "15 г",
    brand: "syngenta",
    brandName: "Belchim Crop Protection / ISK",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["домати", "овощни", "зеленчуци", "житни"],
    cropsDisplay: "Ябълки, Праскови, Домати, Краставици, Житни",
    active: "Флоникамид (500 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "14 дни (Овощни) / 1 ден (Оранжерийни зеленчуци)",
    reg: "БАБХ: № 00895-ПРЗ",
    badge: "Стоп-Хранене",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Спира храненето на листните въшки до 60 минути след пръскане. Не засяга полезните хищни насекоми (калинки, златоочици).",
    rates: [
      { val: 14, label: "14 г/дка (Всички видове листни въшки по овощни)" },
      { val: 10, label: "10 г/дка (Оранжерийна белокрилка)" }
    ],
    packSizes: [
      { label: "15 г", price: 8.74, unit: "€ 9.20 / 15 г", default: true },
      { label: "140 г", price: 45.60, unit: "€ 48.00 / 140 г" },
      { label: "500 г", price: 137.75, unit: "€ 145.00 / 500 г" }
    ],
    rating: 5.0,
    reviewsCount: 41,
    inStock: true
  },
  {
    id: "avant-150-ec",
    name: "Авант 150 ЕК",
    title: "Авант 150 ЕК – ови-ларвицид с индоксакарб за лозя и овощни",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 36.10,
    unit: "250 мл",
    brand: "corteva",
    brandName: "FMC Agricultural Solutions",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "овощни", "домати"],
    cropsDisplay: "Лозя, Ябълки, Домати, Царевица",
    active: "Индоксакарб (150 г/л)",
    formulation: "ЕК (Емулсионен концентрат)",
    quarantine: "10 дни (Лозя) / 7 дни (Ябълки) / 3 дни (Домати)",
    reg: "БАБХ: № 00844-ПРЗ",
    badge: "Премиум Гъсеници",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Специфичен за борба с гроздови молци, нощенки и плодови червеи. Устойчив на високи летни температури и отмиване от дъжд.",
    rates: [
      { val: 25, label: "25 мл/дка (Шарен гроздов молец по лозя)" },
      { val: 33, label: "33 мл/дка (Ябълков плодов червей)" }
    ],
    packSizes: [
      { label: "250 мл", price: 36.10, unit: "€ 38.00 / 250 мл", default: true },
      { label: "1 л", price: 128.25, unit: "€ 135.00 / 1 л" }
    ],
    rating: 4.8,
    reviewsCount: 22,
    inStock: true
  },
  {
    id: "vertimec-018-ec",
    name: "Вертимек 018 ЕК",
    title: "Вертимек 018 ЕК – акарицид и инсектицид с абамектин",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 8.46,
    unit: "100 мл",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Ябълки, Праскови, Домати, Краставици",
    active: "Абамектин (18 г/л)",
    formulation: "ЕК (Емулсионен концентрат)",
    quarantine: "3 дни (Зеленчуци) / 14 дни (Овощни) / 28 дни (Лозя)",
    reg: "БАБХ: № 00530-ПРЗ",
    badge: "№1 Акари",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Трансламинарен инсекто-акарицид от естествен произход. Прониква в листата и унищожава червения паяк, ериофидните акари и миниращите мухи.",
    rates: [
      { val: 100, label: "100-120 мл/дка (Паяжинообразуващ и жълт лозов акар)" },
      { val: 80, label: "80 мл/дка (Миниращи мухи и трипси)" }
    ],
    packSizes: [
      { label: "100 мл", price: 8.46, unit: "€ 8.90 / 100 мл", default: true },
      { label: "1 л", price: 58.90, unit: "€ 62.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 54,
    inStock: true
  },
  {
    id: "nissorun-10-wp",
    name: "Нисоран 10 ВП",
    title: "Нисоран 10 ВП – специфичен акарицид с хормонално действие",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 6.17,
    unit: "50 г",
    brand: "nippon",
    brandName: "Nippon Soda (Япония)",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни", "зеленчуци"],
    cropsDisplay: "Лозя, Ябълка, Соя, Домати, Краставици",
    active: "Хекситиазокс (100 г/кг)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "30 дни (Лозя и ябълки) / 3 дни (Краставици)",
    reg: "БАБХ: № 00219-ПРЗ",
    badge: "Стерилизира Яйцата",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Унищожава яйцата и ларвите на червения овощен и паяжинообразуващия акар и стерилизира възрастните женски с последействие до 50 дни.",
    rates: [
      { val: 50, label: "50 г/дка (Червен овощен акар Panonychus ulmi)" },
      { val: 80, label: "80 г/дка (При силно нападение)" }
    ],
    packSizes: [
      { label: "50 г", price: 6.17, unit: "€ 6.50 / 50 г", default: true },
      { label: "100 г", price: 11.21, unit: "€ 11.80 / 100 г" },
      { label: "500 г", price: 41.80, unit: "€ 44.00 / 500 г" }
    ],
    rating: 4.8,
    reviewsCount: 38,
    inStock: true
  },
  {
    id: "ortus-5-sc",
    name: "Ортус 5 СК",
    title: "Ортус 5 СК – нокдаун акарицид с фенпироксимат",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 6.84,
    unit: "50 мл",
    brand: "nippon",
    brandName: "Nihon Nohyaku / Sumi Agro",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Ябълки, Праскови",
    active: "Фенпироксимат (50 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "14 дни (Лозя и овощни)",
    reg: "БАБХ: № 00488-ПРЗ",
    badge: "Бърз Стоп",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Бързо парализира подвижните форми на акарите с дълго остатъчно действие върху листата.",
    rates: [
      { val: 100, label: "100 мл/дка (Паяжинообразуващ и ръждив акар)" }
    ],
    packSizes: [
      { label: "50 мл", price: 6.84, unit: "€ 7.20 / 50 мл", default: true },
      { label: "1 л", price: 65.55, unit: "€ 69.00 / 1 л" }
    ],
    rating: 4.8,
    reviewsCount: 27,
    inStock: true
  },
  {
    id: "masai-wp",
    name: "Масай ВП",
    title: "Масай ВП – тебуфенпирад срещу всички стадии на акарите",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 11.88,
    unit: "100 г",
    brand: "basf",
    brandName: "BASF SE (Германия)",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "овощни"],
    cropsDisplay: "Лозя, Ябълки, Круши, Праскови",
    active: "Тебуфенпирад (200 г/кг)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "21 дни (Лозя) / 7 дни (Ябълки)",
    reg: "БАБХ: № 00788-ПРЗ",
    badge: "Всички Стадии",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Унищожава яйца, ларви, нимфи и възрастни акари. Не се влияе от температурните колебания.",
    rates: [
      { val: 25, label: "25 г/дка (Лозов акар и жълт лозов акар)" },
      { val: 30, label: "30 г/дка (Червен овощен акар)" }
    ],
    packSizes: [
      { label: "100 г", price: 11.88, unit: "€ 12.50 / 100 г", default: true },
      { label: "500 г", price: 51.30, unit: "€ 54.00 / 500 г" }
    ],
    rating: 4.9,
    reviewsCount: 30,
    inStock: true
  },
  {
    id: "closer-120-sc",
    name: "Клоузър 120 СК",
    title: "Клоузър 120 СК – иновация Isoclast Active срещу листни въшки",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 7.69,
    unit: "50 мл",
    brand: "corteva",
    brandName: "Corteva Agriscience",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["зеленчуци", "картофи", "овощни"],
    cropsDisplay: "Домати, Пипер, Зеле, Картофи, Ябълки",
    active: "Сулфоксафлор (120 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "1 ден (Домати) / 7 дни (Зеле и картофи)",
    reg: "БАБХ: № 01610-ПРЗ",
    badge: "Най-Купуван",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Нова химична група сулфоксимини. Ликвидира дори популации на листни въшки и белокрилки, устойчиви на неоникотиноиди.",
    rates: [
      { val: 20, label: "20 мл/дка (Листни въшки по зеленчуци)" },
      { val: 40, label: "40 мл/дка (Белокрилка и щитоносни въшки)" }
    ],
    packSizes: [
      { label: "50 мл", price: 7.69, unit: "€ 8.10 / 50 мл", default: true },
      { label: "250 мл", price: 32.30, unit: "€ 34.00 / 250 мл" }
    ],
    rating: 4.9,
    reviewsCount: 48,
    inStock: true
  },
  {
    id: "voliam-targo",
    name: "Волиам Тарго 063 СК",
    title: "Волиам Тарго 063 СК – хлорантранилипрол и абамектин",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 46.55,
    unit: "250 мл",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["домати", "овощни"],
    cropsDisplay: "Домати, Ябълки, Круши",
    active: "Хлорантранилипрол (45 г/л) + Абамектин (18 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "3 дни (Домати) / 14 дни (Ябълки)",
    reg: "БАБХ: № 01240-ПРЗ",
    badge: "2-в-1 Комплекс",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "Едновременен пълен контрол върху гъсеници (миниращ молец, нощенки) и акари само с едно третиране.",
    rates: [
      { val: 80, label: "80 мл/дка (Tuta absoluta и червен паяк по домати)" }
    ],
    packSizes: [
      { label: "250 мл", price: 46.55, unit: "€ 49.00 / 250 мл", default: true },
      { label: "1 л", price: 169.10, unit: "€ 178.00 / 1 л" }
    ],
    rating: 5.0,
    reviewsCount: 23,
    inStock: true
  },
  {
    id: "delegate-250-wg",
    name: "Делегат 250 ВГ",
    title: "Делегат 250 ВГ – спинетозис инсектицид с биопроизход Jemvelva",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 28.02,
    unit: "100 г",
    brand: "corteva",
    brandName: "Corteva Agriscience",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["овощни", "лозя"],
    cropsDisplay: "Ябълки, Круши, Праскови, Лозя",
    active: "Спинеторам (250 г/кг)",
    formulation: "ВГ (Вододиспергируеми гранули)",
    quarantine: "7 дни (Овощни) / 14 дни (Лозя)",
    reg: "БАБХ: № 01655-ПРЗ",
    badge: "Президентска Награда",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Спечелил Green Chemistry награда. Справя се безупречно с трипси, плодови червеи и листозавивачки без кръстосана резистентност.",
    rates: [
      { val: 30, label: "30 г/дка (Ябълков плодов червей и крушова листна бълха)" }
    ],
    packSizes: [
      { label: "100 г", price: 28.02, unit: "€ 29.50 / 100 г", default: true },
      { label: "1 кг", price: 247.00, unit: "€ 260.00 / 1 кг" }
    ],
    rating: 4.9,
    reviewsCount: 16,
    inStock: true
  },
  {
    id: "laser-240-sc",
    name: "Лазер 240 СК БИО",
    title: "Лазер 240 СК – биоинсектицид със спинозад за органично земеделие",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 10.92,
    unit: "50 мл",
    brand: "corteva",
    brandName: "Corteva Agriscience",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["домати", "картофи", "лозя", "овощни"],
    cropsDisplay: "Домати, Картофи, Пипер, Лозя, Овощни",
    active: "Спинозад (240 г/л)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "3 дни (Зеленчуци) / 7 дни (Лозя)",
    reg: "БАБХ: № 00612-ПРЗ",
    badge: "100% БИО",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Продукт на естествена ферментация от почвена актиномицета Saccharopolyspora spinosa. Свободно разрешен за био производство.",
    rates: [
      { val: 20, label: "20 мл/дка (Колорадски бръмбар и нощенки)" },
      { val: 40, label: "40 мл/дка (Западен цветен трипс)" }
    ],
    packSizes: [
      { label: "50 мл", price: 10.92, unit: "€ 11.50 / 50 мл", default: true },
      { label: "250 мл", price: 43.70, unit: "€ 46.00 / 250 мл" }
    ],
    rating: 4.9,
    reviewsCount: 39,
    inStock: true
  },
  {
    id: "neem-azal-ts",
    name: "Ним Азал Т/С БИО",
    title: "Ним Азал Т/С – системен органичен инсектицид от дървото Нийм",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 9.31,
    unit: "100 мл",
    brand: "amitica",
    brandName: "Trifolio-M / Амитица",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["зеленчуци", "картофи", "овощни"],
    cropsDisplay: "Всички зеленчуци, Картофи, Овошки, Цветя",
    active: "Азадирахтин А (10 г/л)",
    formulation: "ЕК (Емулсионен концентрат)",
    quarantine: "3 дни",
    reg: "БАБХ: № 01390-ПРЗ",
    badge: "Био Еталон",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Спира линеенето и размножаването на вредителите. Силно репелентно действие срещу въшки, белокрилка и колорадски бръмбар.",
    rates: [
      { val: 250, label: "250-300 мл/дка (Листни въшки, белокрилка, трипси)" }
    ],
    packSizes: [
      { label: "100 мл", price: 9.31, unit: "€ 9.80 / 100 мл", default: true },
      { label: "1 л", price: 74.10, unit: "€ 78.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 51,
    inStock: true
  },
  {
    id: "lepinox-plus",
    name: "Лепинокс Плюс БИО",
    title: "Лепинокс Плюс – биологичен инсектицид срещу гъсеници",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 6.55,
    unit: "100 г",
    brand: "amitica",
    brandName: "CBC Europe / Амитица",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["зеленчуци", "овощни", "лозя"],
    cropsDisplay: "Зеленчуци, Овощни, Лозя, Царевица",
    active: "Bacillus thuringiensis subsp. kurstaki (щам EG 2348)",
    formulation: "ВП (Намокрящ се прах)",
    quarantine: "0 дни (Без карантинен срок)",
    reg: "БАБХ: № 01530-ПРЗ",
    badge: "0 Дни Карантина",
    image: "https://images.unsplash.com/photo-1592417817098-8f3d6910985c?auto=format&fit=crop&w=600&q=80",
    desc: "100% биологичен селективен бактериален препарат срещу гъсеници. Безопасен за хора, птици и пчели. Може да се бере веднага!",
    rates: [
      { val: 100, label: "100 г/дка (Нощенки, листозавивачки, пеперуди)" }
    ],
    packSizes: [
      { label: "100 г", price: 6.55, unit: "€ 6.90 / 100 г", default: true },
      { label: "1 кг", price: 53.20, unit: "€ 56.00 / 1 кг" }
    ],
    rating: 5.0,
    reviewsCount: 67,
    inStock: true
  },
  {
    id: "limocide",
    name: "Лимоцид БИО",
    title: "Лимоцид – биофунгицид, инсектицид и акарицид с портокалово масло",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 13.21,
    unit: "200 мл",
    brand: "amitica",
    brandName: "Vivagro / Амитица",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["лозя", "зеленчуци", "овощни"],
    cropsDisplay: "Лозя, Домати, Краставици, Цитруси, Овощни",
    active: "Портокалово масло (60 г/л)",
    formulation: "МЕ (Микроемулсия)",
    quarantine: "1 ден",
    reg: "БАБХ: № 01680-ПРЗ",
    badge: "3-в-1 Био",
    image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80",
    desc: "Разрушава восъчната кутикула на насекомите (белокрилка, трипс, акари) и клетъчните стени на гъбните спори (оидиум). Оставя свеж цитрусов аромат.",
    rates: [
      { val: 200, label: "200-400 мл/дка (Белокрилки, трипси, оидиум)" }
    ],
    packSizes: [
      { label: "200 мл", price: 13.21, unit: "€ 13.90 / 200 мл", default: true },
      { label: "1 л", price: 56.05, unit: "€ 59.00 / 1 л" }
    ],
    rating: 4.9,
    reviewsCount: 43,
    inStock: true
  },
  {
    id: "madex-twin",
    name: "Мадекс Твин БИО",
    title: "Мадекс Твин – специфичен грануловирус за плодови червеи",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 18.52,
    unit: "100 мл",
    brand: "amitica",
    brandName: "Andermatt Biocontrol",
    useCategory: "nonprof",
    useCategoryName: "Непрофесионална категория",
    crops: ["овощни"],
    cropsDisplay: "Ябълки, Круши, Дюли, Орехи",
    active: "Cydia pomonella Granulovirus (CpGV-V15)",
    formulation: "СК (Суспензионен концентрат)",
    quarantine: "0 дни",
    reg: "БАБХ: № 01433-ПРЗ",
    badge: "Вирусна Защита",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80",
    desc: "Високоселективен за ябълков плодов червей и източен плодов червей. Предава се между поколенията на вредителя.",
    rates: [
      { val: 10, label: "10 мл/дка (При излюпване на всяко поколение червеи)" }
    ],
    packSizes: [
      { label: "100 мл", price: 18.52, unit: "€ 19.50 / 100 мл", default: true }
    ],
    rating: 5.0,
    reviewsCount: 26,
    inStock: true
  },
  {
    id: "affirm-095-sg",
    name: "Афирм 095 СГ",
    title: "Афирм 095 СГ – емамектин бензоат срещу листозавивачки и молци",
    category: "insecticides",
    categoryName: "Инсектициди",
    price: 13.49,
    unit: "100 г",
    brand: "syngenta",
    brandName: "Syngenta Crop Protection AG",
    useCategory: "prof",
    useCategoryName: "II Професионална категория",
    crops: ["лозя", "домати", "овощни"],
    cropsDisplay: "Лозя, Ябълки, Домати, Пипер",
    active: "Емамектин бензоат (9.5 г/кг)",
    formulation: "СГ (Разтворими гранули)",
    quarantine: "7 дни (Лозя и овощни) / 3 дни (Домати)",
    reg: "БАБХ: № 01130-ПРЗ",
    badge: "Експресен Стоп",
    image: "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
    desc: "Активира се при поглъщане от гъсениците, причинявайки необратима парализа за броени часове.",
    rates: [
      { val: 150, label: "150 г/дка (Шарен гроздов молец, доматен молец)" }
    ],
    packSizes: [
      { label: "100 г", price: 13.49, unit: "€ 14.20 / 100 г", default: true },
      { label: "1 кг", price: 112.10, unit: "€ 118.00 / 1 кг" }
    ],
    rating: 4.9,
    reviewsCount: 31,
    inStock: true
  }
];

window.AGRO_CATALOG_DATA.push(...INSECTICIDES);
